### ISSUE TITLE
What's the best result have you got by training the network using this code?

### ISSUE THREAD

**Issue by CodeLHY** [Tianxiaomo/pytorch-YOLOv4#10]
Hi, @Tianxiaomo 
Nice work!
I'm attracted by your work, and could you please tell me the best result have you got by training the network using this code?

**Comment by Tianxiaomo** [comment]
I'm sorry I haven't had time to train the model yet, but you can test it using the trained weights given by AlexeyAB.

**Comment by CodeLHY** [comment]
Thanks for your timely reply!
I'll close this issue.
