### ISSUE TITLE
error while running models.py with custom trained model

### ISSUE THREAD

**Issue by imprashr** [Tianxiaomo/pytorch-YOLOv4#101]
Traceback (most recent call last):
  File "models.py", line 462, in <module>
    boxes = do_detect(model, sized, 0.5, n_classes,0.4, use_cuda)
  File "/home/ubuntu/pytorch-YOLOv4/tool/torch_utils.py", line 247, in do_detect
    output[-1].append(boxes_and_confs[i][1].cpu().detach().numpy())
IndexError: index 1 is out of bounds for dimension 0 with size 1
any help appreciated!

**Comment by YSJ305** [comment]
我也有同样的疑问，希望路过的大佬可以帮忙解答一下

**Comment by PL1296** [comment]
我也是这个问题

**Comment by JavierClearImageAI** [comment]
The same here. The bbox from outputs is not a bbox, its a big Tensor. Perhaps the feature vector?

>>>type(boxes_and_confs)
<class 'list'>
>>>len(boxes_and_confs)
1
>>> type(boxes_and_confs[0])
<class 'torch.Tensor'>
>>> print(boxes_and_confs[0].shape)
torch.Size([1, 21, 76, 76])

**Comment by zhangliyuan0225** [comment]
The same issue.
boxes_and_confs[0].shape= [4,24,76,76].
len(boxes_and_confs)=3.
follow boxes_and_confs,
[4,
24,#=(4+1+n_classes)*3
76,76]
In Yolo_loss.forward, trans it be output to cal loss, but it's too hard for me to fix the issue with it.

**Comment by jersonal** [comment]
me too

**Comment by YSJ305** [comment]
大家这个问题解决了吗

**Comment by ersheng-ai** [comment]
This problem of `models.py` I think it is now fixed.
I will close this issue.
Open new issues if you have got new problems.
