### ISSUE TITLE
medels.py运行不通

### ISSUE THREAD

**Issue by YSJ305** [Tianxiaomo/pytorch-YOLOv4#104]

**Comment by ersheng-ai** [comment]
Yes, this is a bug.
You can try to manually add yolo_layer defined in **`yolo_layer.py`** into this model to run.
If you just want to run an inference demo, just run demo.py.
I will fix it later.

**Comment by YSJ305** [comment]
> This model is **NOT** supposed to include yolo layer.
> But you can try to manually add yolo_layer defined in **`yolo_layer.py`** into this model to do inference.
> If you just want to run an inference demo, run **`demo.py`**.

可是model.s.py中的yolo_layer已经注释掉了啊

**Comment by ersheng-ai** [comment]
> > This model is **NOT** supposed to include yolo layer.
> > But you can try to manually add yolo_layer defined in **`yolo_layer.py`** into this model to do inference.
> > If you just want to run an inference demo, run **`demo.py`**.
> 
> 可是model.s.py中的yolo_layer已经注释掉了啊

Pull the latest code. Set **`yolo_layer_included=True`** if you want to do inference.
