### ISSUE TITLE
torch_utils中do_detect的这几行是不是有错误

### ISSUE THREAD

**Issue by jiangnanLZP** [Tianxiaomo/pytorch-YOLOv4#106]
for i in range(len(boxes_and_confs)):
        output.append([])
        output[-1].append(boxes_and_confs[i][0].cpu().detach().numpy())
        output[-1].append(boxes_and_confs[i][1].cpu().detach().numpy())

报错：
output[-1].append(boxes_and_confs[i][1].cpu().detach().numpy())
IndexError: index 1 is out of bounds for dimension 0 with size 1

疑问：boxes_and_confs是返回的几个fmap， [i][0], [i][1]是什么意思，求解

**Comment by ersheng-ai** [comment]
Model inference output's structure is like this:
```py
[ [boxes1, confs1], [boxes2, confs2], [boxes3, confs3] ]
```
You can read code commends in method **`yolo_forward`** for detailed information about boxes and confs.
