### ISSUE TITLE
onnx推理出错

### ISSUE THREAD

**Issue by myl353** [Tianxiaomo/pytorch-YOLOv4#108]
您好，是训练好pth模型后，将pth模型转为onnx，然后使用demo_onnx.py进行onnx推理，但onnx的输出全是：
[[nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         ...,
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan],
         [nan, nan, nan, ..., nan, nan, nan]],

        [[nan, nan, nan, ..., nan, nan, nan],
....

请问是要修改哪里吗？？我转出的onnx完全没法使用

**Comment by ersheng-ai** [comment]
The model defined in **`models.py`** does not have yolo layers during the training.
Did you include the yolo layer in the trained model like this before converting it into onnx?

```py
if self.yolo_layer_included:
            y1 = self.yolo1(x2)
            y2 = self.yolo2(x10)
            y3 = self.yolo3(x18)

            return [y1, y2, y3]
        
        else:
            return [x2, x10, x18]
```

**Comment by myl353** [comment]
@ersheng-ai 您好，我使用的是5月的一个版本，那个时候yolo默认返回的是[x2, x10, x18]，也就是在使用新版训练时，需要将yolo_layer_included改为true，然后后面转onnx才会有返回值吗？

**Comment by ersheng-ai** [comment]
**`yolo_layer_included = False`** while training

**Comment by myl353** [comment]
训练时，这个是默认为false的，我没有改动过

**Comment by ersheng-ai** [comment]
> 训练时，这个是默认为false的，我没有改动过

**`yolo_layer_included = True`** when do inference and onnx convertion

**Comment by myl353** [comment]
我转onnx是也只是修改了文件路径，其它没有进行改动，可就是没有返回值

**Comment by myl353** [comment]
您好，在darknet2onnx.py中模型是：model = Darknet(cfgfile)，是从cfg构建出来的Darknet模型，请问在哪里可以设置yolo_layer_included = True ，

**Comment by ersheng-ai** [comment]
The darknet2onnx demo includes yolo_layer already

**Comment by myl353** [comment]
好的，麻烦您了

**Comment by ersheng-ai** [comment]
Pull the latest code and try `demo_pytorch2onnx.py` for your own trained model
