### ISSUE TITLE
yolov4.pth

### ISSUE THREAD

**Issue by zys1994** [Tianxiaomo/pytorch-YOLOv4#11]
can you provide yolov4.pth

**Comment by sporadicCactus** [comment]
I made a more pytorch-ish implementation and ported the weights:
https://github.com/sporadicCactus/pytorch_headless_YOLOv4

Dropped the last two layers though (prediction head).

Maybe you'll find it useful.

**Comment by Tianxiaomo** [comment]
Has been updated.
