### ISSUE TITLE
when train my own dataset model,run models.py for inference ,then error happen.

### ISSUE THREAD

**Issue by runauto** [Tianxiaomo/pytorch-YOLOv4#110]
when inference with the model yolov4.pth,the result is right. but inference with my own model (classnum=1), the error info as:
`>python models.py 1 ./Yolov4_epoch1.pth C:\Users\Desktop\tmp\img004013.jpg ./data/danerous.names
Traceback (most recent call last):
  File "models.py", line 470, in <module>
    model.load_state_dict(pretrained_dict)
  File "C:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Yolov4:
        Missing key(s) in state_dict: "down1.conv1.conv.0.weight", "down1.conv1.conv.1.weight", "down1.conv1.conv.1.bias", "down1.conv1.conv.1.running_mean", "down1.conv1.conv.1.running_var", `

**Comment by ersheng-ai** [comment]
Check whether names in saved snapshot are consistent with the ones declared in definitions in models.py

**Comment by adrien-jacquot** [comment]
Hey, I found a way to properly load the model (don't ask me why it works):

```python
model = Yolov4(yolov4conv137weight=None, n_classes=1, inference=True)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
if torch.cuda.device_count() > 1:
    model = torch.nn.DataParallel(model)
model.to(device=device)
pretrained_dict = torch.load(model_path, map_location=torch.device('cuda'))
model.load_state_dict(pretrained_dict)
model.cuda()
```
