### ISSUE TITLE
怎么才能用GPU进行训练

### ISSUE THREAD

**Issue by YSJ305** [Tianxiaomo/pytorch-YOLOv4#112]

**Comment by ersheng-ai** [comment]
References:
<https://discuss.pytorch.org/t/train-model-by-using-a-specific-gpu/16923>
<https://zhuanlan.zhihu.com/p/31936740>
<https://www.cnblogs.com/darkknightzh/p/6836568.html>
<https://github.com/pytorch/pytorch/issues/1901>
