### ISSUE TITLE
YoloV5 requires torch >=1.5

### ISSUE THREAD

**Issue by makaveli10** [Tianxiaomo/pytorch-YOLOv4#116]
The new [Ultralytics Yolov5](https://github.com/ultralytics/yolov5) requires torch >= 1.5. I havent yet tried converting the onnx model to TRT engine because I saw [this post](https://forums.developer.nvidia.com/t/iplugin-tensorrt-engine-error-for-ds5-0/123277/13?u=y14uc339) which says torch = 1.5 has some compatibility issues with TRT conversion. So, my question is can we convert this yolov5 from onnx to TRT.
Or do we need to use C++ API and write custom plugins which is a bottleneck in itself?

**Comment by tensorflowt** [comment]
> The new [Ultralytics Yolov5](https://github.com/ultralytics/yolov5) requires torch >= 1.5. I havent yet tried converting the onnx model to TRT engine because I saw [this post](https://forums.developer.nvidia.com/t/iplugin-tensorrt-engine-error-for-ds5-0/123277/13?u=y14uc339) which says torch = 1.5 has some compatibility issues with TRT conversion. So, my question is can we convert this yolov5 from onnx to TRT.
> Or do we need to use C++ API and write custom plugins which is a bottleneck in itself?

Are you saying that yolov5 will need to lower pytorch's version to 1.4 if it wants to switch to onNX? Otherwise, you will encounter problems similar to the following:
https://github.com/TrojanXu/yolov5-tensorrt/issues/35

**Comment by makaveli10** [comment]
@tensorflowt you can convert successfully using torch 1.4 on the same repo. Just make sure you are using the correct commit when converting to onnx.
