### ISSUE TITLE
请问如何修改demo_trt.py使其适应大批量识别

### ISSUE THREAD

**Issue by 17702513221** [Tianxiaomo/pytorch-YOLOv4#120]
我自行修改了一个版本
[[[0.5532519, 0.6153389, 0.8914345, 0.82043, 0.96487856, 0.96487856, 0]]]
person: 0.964879
Shape of the network input:  (5, 3, 320, 320)
Length of inputs:  1
[TensorRT] WARNING: Explicit batch network detected and batch size specified, use enqueue without batch size instead.
Len of outputs:  1
可是输出还是为1批次的。
顺便希望加微信群，我可以尝试完成deepstream的移植工作，希望进群讨论

**Comment by 17702513221** [comment]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::enqueue::292, condition: batchSize > 0 && batchSize <= mEngine.getMaxBatchSize(). Note: Batch size was: 5, but engine max batch size was: 1
我使用了./trtexec --onnx=yolov4_5_3_320_320.onnx --explicitBatch --saveEngine=yolov4_320_5.trt --fp16

**Comment by ersheng-ai** [comment]
Which version of TensorRT are you now using?

**Comment by 17702513221** [comment]
7.0

**Comment by ersheng-ai** [comment]
The output of engine is a list of numpy arrays. Length of this list is 1.
Shape of this unique tensor should be **`[batch, num_boxes, 4 + classes]`**

The ONNX model should have the same batch size.

**Comment by 17702513221** [comment]
我已经使用了最新的代码，修改了
def do_inference(context, bindings, inputs, outputs, stream, batch_size=5):
报错
[TensorRT] ERROR: Parameter check failed at: engine.cpp::enqueue::292, condition: batchSize > 0 && batchSize <= mEngine.getMaxBatchSize(). Note: Batch size was: 5, but engine max batch size was: 1

**Comment by 17702513221** [comment]
我改了这两个地方，可是输出batch还是1
img_in = np.vstack((img_in,img_in,img_in,img_in,img_in))#模拟5路帧识别
def do_inference(context, bindings, inputs, outputs, stream, batch_size=5):
中间有报警
[TensorRT] WARNING: Explicit batch network detected and batch size specified, use enqueue without batch size instead.

**Comment by ersheng-ai** [comment]
What is batch size of your ONNX where your engine is from?

**Comment by 17702513221** [comment]
python3 demo_darknet2onnx.py cfg/yolov4.cfg yolov4.weights data/dog.jpg 5
./trtexec --onnx=yolov4_5_3_320_320.onnx --maxBatch=5  --saveEngine=yolov4_320_5.trt --fp16

**Comment by 17702513221** [comment]
请问能加微信进群讨论吗

**Comment by ersheng-ai** [comment]
`--maxBatch` Argument is deprecated and gonna be removed. Please use `--explicitBatch` argument so that engine can copy batch size from ONNX directly.

**Comment by 17702513221** [comment]
当我使用
./trtexec --onnx=yolov4_5_3_320_320.onnx --explicitBatch=5 --saveEngine=yolov4_320_5.trt --fp16
运行得到错误
Shape of the network input:  (5, 3, 320, 320)
Length of inputs:  1
[TensorRT] ERROR: Parameter check failed at: engine.cpp::enqueue::292, condition: batchSize > 0 && batchSize <= mEngine.getMaxBatchSize(). Note: Batch size was: 5, but engine max batch size was: 1
Len of outputs:  1
(1, 31500, 84)

**Comment by ersheng-ai** [comment]
There is no value for `--explicitBatch`, please read README.md carefully.

**Comment by 17702513221** [comment]
使用了
./trtexec --onnx=yolov4_5_3_320_320.onnx --explicitBatch  --saveEngine=yolov4_320_5.trt --fp16
还是会有这个报警
Shape of the network input:  (5, 3, 320, 320)
Length of inputs:  1
[TensorRT] WARNING: Explicit batch network detected and batch size specified, use enqueue without batch size instead.
Len of outputs:  1
同时如果改了
def do_inference(context, bindings, inputs, outputs, stream, batch_size=5):
会报错：
Post processing total : 0.008465
-----------------------------------
[[]]
Shape of the network input:  (5, 3, 320, 320)
Length of inputs:  1
[TensorRT] ERROR: Parameter check failed at: engine.cpp::enqueue::292, condition: batchSize > 0 && batchSize <= mEngine.getMaxBatchSize(). Note: Batch size was: 5, but engine max batch size was: 1
Len of outputs:  1
(1, 31500, 84)

**Comment by ersheng-ai** [comment]
What is batch size of your ONNX?

**Comment by ersheng-ai** [comment]
![qr](https://user-images.githubusercontent.com/62684483/85361902-b744ba80-b54f-11ea-8e24-4d2264d7a76e.jpg)
