### ISSUE TITLE
mix数据增广不是用于目标检测而是用于训练分类网络

### ISSUE THREAD

**Issue by zhaoyue3513247** [Tianxiaomo/pytorch-YOLOv4#121]
论文中用的mix是训练basenet的吧。。。

**Comment by Tianxiaomo** [comment]
https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/4a5b6c160dad4fa59e6c013ce5e4c9acd40b36d6/cfg.py#L57-L64

https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/4a5b6c160dad4fa59e6c013ce5e4c9acd40b36d6/dataset.py#L270-L278

https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/4a5b6c160dad4fa59e6c013ce5e4c9acd40b36d6/dataset.py#L351-L380

其实在训练yolo的时候并没有用到mixup

**Comment by nikhil031294** [comment]
> https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/4a5b6c160dad4fa59e6c013ce5e4c9acd40b36d6/cfg.py#L57-L64
> 
> https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/4a5b6c160dad4fa59e6c013ce5e4c9acd40b36d6/dataset.py#L270-L278
> 
> https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/4a5b6c160dad4fa59e6c013ce5e4c9acd40b36d6/dataset.py#L351-L380
> 
> In fact, mixup is not used when training yolo

IF we set mosaic =1, then mixup will be 3 right?
And then it will be used in the get_item?
