### ISSUE TITLE
demo_trt cannot inference on multiple images

### ISSUE THREAD

**Issue by makaveli10** [Tianxiaomo/pytorch-YOLOv4#122]
I tried to inference on multiple images in a loop. It copies output of the first image into the output of all others!! Is it a bug? Or there is a different way to do multi-inference?

**Comment by 17702513221** [comment]
I want to inference on multiple images too,but i get a outputs, can you tell me how to get tesult.
this is my code:
detect(engine, context, buffers, frame1,frame2,frame3,frame4,frame5, image_size, num_classes):
resized = cv2.resize(frame5, (IN_IMAGE_W, IN_IMAGE_H), interpolation=cv2.INTER_LINEAR)
    img_in = cv2.cvtColor(resized, cv2.COLOR_BGR2RGB)
    img_in = np.transpose(img_in, (2, 0, 1)).astype(np.float32)
    img_in = np.expand_dims(img_in, axis=0)
    img_in /= 255.0
    img_in = np.ascontiguousarray(img_in)
    img_in_5=img_in
img_in = np.vstack((img_in_1,img_in_2,img_in_3,img_in_4,img_in_5))

**Comment by 17702513221** [comment]
I want to inference on multiple images too,but i get a error, can you tell me how to get result.
this is my code:
detect(engine, context, buffers, frame1,frame2,frame3,frame4,frame5, image_size, num_classes):
resized = cv2.resize(frame5, (IN_IMAGE_W, IN_IMAGE_H), interpolation=cv2.INTER_LINEAR)
img_in = cv2.cvtColor(resized, cv2.COLOR_BGR2RGB)
img_in = np.transpose(img_in, (2, 0, 1)).astype(np.float32)
img_in = np.expand_dims(img_in, axis=0)
img_in /= 255.0
img_in = np.ascontiguousarray(img_in)
img_in_5=img_in
img_in = np.vstack((img_in_1,img_in_2,img_in_3,img_in_4,img_in_5))

**Comment by ersheng-ai** [comment]
> I tried to inference on multiple images in a loop. It copies output of the first image into the output of all others!! Is it a bug? Or there is a different way to do multi-inference?

Add this line into beginning of function **`plot_boxes_cv2()`** in **`tool/utils.py`** or just simply pull the latest source code.

```py
    img = np.copy(img)
```

**Comment by makaveli10** [comment]
@ersheng-ai so I am not actually using yolov4 but yolov5 TensorRT engine. But to inference on the engine I used demotrt. So, when I feed one image after the other the output of first image is copied to all the others that follow!!

**Comment by HtutLynn** [comment]
@makaveli10 , Were you able to fix it? I am trying to do inferencing on the video by using opencv and having the same problem too. 
Code : 
```
        if os.path.exists(video_path):
            video_src = video_path

        # initate video reading pipeline
        cap = cv2.VideoCapture(video_src)
        while True:

            ret, frame = cap.read()
            if not ret:
                break

            boxes = detect(context, buffers, frame, frame_size, num_classes)
            print(boxes)
            # boxes = boxes = filterout(boxes[0], class_id=0)

            namesfile = 'data/coco.names'

            class_names = load_class_names(namesfile)
            inferred_frame = plot_boxes_cv2(frame, boxes[0], class_names=class_names)
            cv2.imshow("Inferred by TensorRT", inferred_frame)
            if cv2.waitKey(1) & 0xFF == ord('q'): 
                break

        cap.release()
        cv2.destroyAllWindows()
```

**Comment by gaozheng-tech** [comment]
@HtutLynn Hello, have you solved this problem?

**Comment by makaveli10** [comment]
> @HtutLynn Hello, have you solved this problem?

Hey sorry i missed your reply, can you try frame.copy() 
`boxes = detect(context, buffers, frame.copy(), frame_size, num_classes)`
