### ISSUE TITLE
Save each bounding boxes as seperate image

### ISSUE THREAD

**Issue by palindrome1311** [Tianxiaomo/pytorch-YOLOv4#123]
Please help me saving each bounding box as a separate image!

**Comment by ersheng-ai** [comment]
Slice operations of numpy can help you crop bounding boxes out from the source image.
You can do this to crop a bounding box **`[x1, y1, x2, y2]`**:

**`cropped  = source_image[y1 : y2 + 1, x1 : x2 + 1]`**
