### ISSUE TITLE
opencv error

### ISSUE THREAD

**Issue by hushuai1** [Tianxiaomo/pytorch-YOLOv4#126]
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by E-Dreamer-LQ** [comment]
@hushuai1 @Tianxiaomo I have the same problem, emmm, How to fix it ?  Thanks

**Comment by doduythao** [comment]
the path for open image is corrupted due to join base dir with content in train.txt. make sure -dir default='' and train.txt should contains absolute path.
