### ISSUE TITLE
What is conv.137?

### ISSUE THREAD

**Issue by model-collapse** [Tianxiaomo/pytorch-YOLOv4#131]
The second weight file provided is called "yolov4.conv.137.pth". Does it mean the smaller weight version of yolov4? 
According to models.py, the path of conv.137 file can be passed to the init function of YoloV4. And the code shows like this:

```
if yolov4conv137weight:
            _model = nn.Sequential(self.down1, self.down2, self.down3, self.down4, self.down5, self.neek)
            pretrained_dict = torch.load(yolov4conv137weight)

            model_dict = _model.state_dict()
            # 1. filter out unnecessary keys
            pretrained_dict = {k1: v for (k, v), k1 in zip(pretrained_dict.items(), model_dict)}
            # 2. overwrite entries in the existing state dict
            model_dict.update(pretrained_dict)
            _model.load_state_dict(model_dict)
```

We can see that all the weights were fed to the temporary variable _model and used no where.
Besides, the script can be executed with no error but no boxing box is found.

Any ideas?

**Comment by Tianxiaomo** [comment]
yolov4.conv.137.pth is just the other part of yolov4 without yololayer, if you train your own dataset, you can use it as the weight with the training
