### ISSUE TITLE
no BBOX on the predictions.jpg

### ISSUE THREAD

**Issue by asian3** [Tianxiaomo/pytorch-YOLOv4#132]
I can run the Demo
but there is no bbox ouput on the picture predictions.jpg.
here is the Demo result on CPU:

-----------------------------------
           Preprocess : 0.014960
      Model Inference : 7.035183
-----------------------------------
-----------------------------------
       max and argmax : 0.012965
                  nms : 0.000000
Post processing total : 0.012965
-----------------------------------
./data/dog.jpg: Predicted in 7.415165 seconds.
save plot results to predictions.jpg

**Comment by wangyong5123** [comment]
i have same problem

**Comment by ersheng-ai** [comment]
Please list detailed information of your configurations and operations step by step.

**Comment by weiyinchiang** [comment]
> I have same problem

Hi! It works when I did
 python demo.py -weightfile ./weight/yolov4.weights -imgfile ./data/dog.jpg

**Comment by wangyong5123** [comment]
> > I have same problem
> 
> Hi! It works when I run
> python demo.py -weightfile ./weight/yolov4.weights -imgfile ./data/dog.jpg
> 
> or
> 
> python models.py 80 ./weight/yolov4.pth ./data/dog.jpg 576 768


Thanks, it works
before  cmdline  error **python demo.py -weightfile yolov4.pth -imgfile ./data/dog.jpg**   no BBox on the predictions.jpg

**Comment by Jinhui-Qin** [comment]
> > I have same problem
> 
> Hi! It works when I run
> python demo.py -weightfile ./weight/yolov4.weights -imgfile ./data/dog.jpg
> 
> or
> 
> python models.py 80 ./weight/yolov4.pth ./data/dog.jpg 576 768

second command works!
