### ISSUE TITLE
demo_trt.py Running error

### ISSUE THREAD

**Issue by qybing** [Tianxiaomo/pytorch-YOLOv4#134]
[TensorRT] ERROR: INVALID_CONFIG: The engine plan file is generated on an incompatible device, expecting compute 7.5 got compute 7.0, please rebuild.
[TensorRT] ERROR: engine.cpp (1407) - Serialization Error in deserialize: 0 (Core engine deserialization failure)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "demo_trt.py", line 195, in <module>
    main(engine_path, image_path, image_size)
  File "demo_trt.py", line 114, in main
    with get_engine(engine_path) as engine, engine.create_execution_context() as context:
AttributeError: __enter__

**Comment by ersheng-ai** [comment]
The engine files generated by a certain version of tensorRT on a specific hardware platform may not be usable for another tensorRT on another different hardware platform.
The engine file is optimized according to the hardware configuration where it is generated, you should re-generate the engine.
