### ISSUE TITLE
how to use the models.py 

### ISSUE THREAD

**Issue by yiwangde** [Tianxiaomo/pytorch-YOLOv4#135]
**_I use my .pth in models.py but erros. Have someone like it? Have Someone knows how to solve it？？？_**

(yolov4) lucas@lucas-B150M-D2VX-SI:~/pytorch-YOLOv4-master$ **python models.py 80 model/Yolov4_epoch10.pth data/dog.jpg 608 608**
Traceback (most recent call last):
  File "models.py", line 475, in <module>
    model.load_state_dict(pretrained_dict)
  File "/home/lucas/.conda/envs/yolov4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Yolov4:
	Missing key(s) in state_dict: "down1.conv1.conv.0.weight", "down1.conv1.conv.1.weight", "down1.conv1.conv.1.bias", "down1.conv1.conv.1.running_mean", "down1.conv1.conv.1.running_var", "down1.conv2.conv.0.weight", "down1.conv2.conv.1.weight", "down1.conv2.conv.1.bias", "down1.conv2.conv.1.running_mean", "down1.conv2.conv.1.running_var", "down1.conv3.conv.0.weight", "down1.conv3.conv.1.weight", "down1.conv3.conv.1.bias",

**Comment by yiwangde** [comment]
****

> **_I use my .pth in models.py but erros. Have someone like it? Have Someone knows how to solve it？？？_**
> 
> (yolov4) lucas@lucas-B150M-D2VX-SI:~/pytorch-YOLOv4-master$ **python models.py 80 model/Yolov4_epoch10.pth data/dog.jpg 608 608**
> Traceback (most recent call last):
> File "models.py", line 475, in
> model.load_state_dict(pretrained_dict)
> File "/home/lucas/.conda/envs/yolov4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
> self.**class**.**name**, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for Yolov4:
> Missing key(s) in state_dict: "down1.conv1.conv.0.weight", "down1.conv1.conv.1.weight", "down1.conv1.conv.1.bias", "down1.conv1.conv.1.running_mean", "down1.conv1.conv.1.running_var", "down1.conv2.conv.0.weight", "down1.conv2.conv.1.weight", "down1.conv2.conv.1.bias", "down1.conv2.conv.1.running_mean", "down1.conv2.conv.1.running_var", "down1.conv3.conv.0.weight", "down1.conv3.conv.1.weight", "down1.conv3.conv.1.bias",

**Comment by Tianxiaomo** [comment]
You can modify this line of code.
https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/d886c8a7810664d25c26f406ef5dc45a0add3e5a/models.py#L474

    model.load_state_dict(pretrained_dict,strict=False)

**Comment by yiwangde** [comment]
> You can modify this line of code.
> https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/d886c8a7810664d25c26f406ef5dc45a0add3e5a/models.py#L474
> 
> ```
> model.load_state_dict(pretrained_dict,strict=False)
> ```

Thank you very much.

**Comment by yiwangde** [comment]
thank you very much. ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Tianxiaomo&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月2日(星期四) 中午1:27
收件人:&nbsp;&quot;Tianxiaomo/pytorch-YOLOv4&quot;<pytorch-YOLOv4@noreply.github.com&gt;;
抄送:&nbsp;&quot;yiwangde&quot;<1375774056@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Tianxiaomo/pytorch-YOLOv4] how to use the models.py  (#135)

**Comment by THEBEST-cloud** [comment]
请问你怎么使用models.pyd的啊

**Comment by Nicoladao** [comment]
> **_I use my .pth in models.py but erros. Have someone like it? Have Someone knows how to solve it？？？_**
> 
> (yolov4) lucas@lucas-B150M-D2VX-SI:~/pytorch-YOLOv4-master$ **python models.py 80 model/Yolov4_epoch10.pth data/dog.jpg 608 608**
> Traceback (most recent call last):
> File "models.py", line 475, in
> model.load_state_dict(pretrained_dict)
> File "/home/lucas/.conda/envs/yolov4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
> self.**class**.**name**, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for Yolov4:
> Missing key(s) in state_dict: "down1.conv1.conv.0.weight", "down1.conv1.conv.1.weight", "down1.conv1.conv.1.bias", "down1.conv1.conv.1.running_mean", "down1.conv1.conv.1.running_var", "down1.conv2.conv.0.weight", "down1.conv2.conv.1.weight", "down1.conv2.conv.1.bias", "down1.conv2.conv.1.running_mean", "down1.conv2.conv.1.running_var", "down1.conv3.conv.0.weight", "down1.conv3.conv.1.weight", "down1.conv3.conv.1.bias",

Do you solve it with modify the code?

**Comment by adrien-jacquot** [comment]
Hey, I found a way to properly load the model (don't ask me why it works):

```python
model = Yolov4(yolov4conv137weight=None, n_classes=1, inference=True)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
if torch.cuda.device_count() > 1:
    model = torch.nn.DataParallel(model)
model.to(device=device)
pretrained_dict = torch.load(model_path, map_location=torch.device('cuda'))
model.load_state_dict(pretrained_dict)
model.cuda()
```
