### ISSUE TITLE
我直接用yolov4.pth进行demo.py测试，过程中发现bbox中的类别数据都问NaN。请问有遇到过吗？

### ISSUE THREAD

**Issue by mengxiangxiang414** [Tianxiaomo/pytorch-YOLOv4#139]
下面是一个bbox的数据。4个坐标值+80个coco类别
tensor([0.0192, 0.0000, 0.0000, 0.0000,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,    nan,
           nan,    nan,    nan], device='cuda:0', grad_fn=<SelectBackward>)

**Comment by Tianxiaomo** [comment]
看一下是不是pytorch版本问题

**Comment by xiaomingzi9527** [comment]
demo.py用的是yolov4.weights，使用yolov4.pth在推理的时候会出现inf数据，导致推理结果错误

**Comment by safehumeng** [comment]
请问问题解决了么，我也遇到这个问题了

**Comment by xiaomingzi9527** [comment]
你用yolov4.weights这个权重文件去跑demo.py应该没问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "safehumeng"<notifications@github.com&gt;; 
发送时间: 2020年12月16日(星期三) 下午5:07
收件人: "Tianxiaomo/pytorch-YOLOv4"<pytorch-YOLOv4@noreply.github.com&gt;; 
抄送: "江俊铭"<1178996366@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Tianxiaomo/pytorch-YOLOv4] 我直接用yolov4.pth进行demo.py测试，过程中发现bbox中的类别数据都问NaN。请问有遇到过吗？ (#139)





 
请问问题解决了么，我也遇到这个问题了

**Comment by safehumeng** [comment]
> 你用yolov4.weights这个权重文件去跑demo.py应该没问题
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "safehumeng"<notifications@github.com&gt;; 发送时间: 2020年12月16日(星期三) 下午5:07 收件人: "Tianxiaomo/pytorch-YOLOv4"<pytorch-YOLOv4@noreply.github.com&gt;; 抄送: "江俊铭"<1178996366@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [Tianxiaomo/pytorch-YOLOv4] 我直接用yolov4.pth进行demo.py测试，过程中发现bbox中的类别数据都问NaN。请问有遇到过吗？ (#139) 请问问题解决了么，我也遇到这个问题了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢啦，当时看到其他issue里面也提到了，已经解决了

**Comment by mengxiangxiang414** [comment]
It is like that this issue has been solved.
