### ISSUE TITLE
急！急！急！您好，我需要计算自己训练的模型的mAP,应该怎么计算呢

### ISSUE THREAD

**Issue by shenghsiaowong** [Tianxiaomo/pytorch-YOLOv4#140]
您好，我需要计算自己训练的模型的mAP,应该怎么计算呢？

**Comment by Tianxiaomo** [comment]
最新提交的已经添加了验证部分

**Comment by Tianxiaomo** [comment]
#80

**Comment by forever208** [comment]
> #80

it would be greatly appreciated if the evaluation on COCO can be added into the readme @Tianxiaomo
