### ISSUE TITLE
在COCO数据集上精度可以达到多少?How much AP can be achieved on coco dataset?

### ISSUE THREAD

**Issue by hujunchao** [Tianxiaomo/pytorch-YOLOv4#149]

**Comment by ersheng-ai** [comment]
You can refer to discussions in following issues:
https://github.com/Tianxiaomo/pytorch-YOLOv4/issues/190
https://github.com/Tianxiaomo/pytorch-YOLOv4/issues/146

**Comment by hujunchao** [comment]
Thanks! I am glad to hear the map of pytorch-yolov4 is close to darknet!
