### ISSUE TITLE
更新

### ISSUE THREAD

**Issue by syg1996419** [Tianxiaomo/pytorch-YOLOv4#15]
你好,小模：
我想请问你一下,你大概多久会更新一下yolov4代码？

**Comment by Tianxiaomo** [comment]
这个不一定，缺的模块都是有空就写写，其他有什么小bug都是大家在issues里提出我就改一下

**Comment by syg1996419** [comment]
因为我现在在看着你的代码学习,所以希望你可以更新快一点,当然这还是要看你的时间了,hh
