### ISSUE TITLE
如何将训练得到的pth文件转换成weights文件

### ISSUE THREAD

**Issue by xidaoliang** [Tianxiaomo/pytorch-YOLOv4#150]

**Comment by Tianxiaomo** [comment]
可以参考darknet2torch.py,都是模型结构解析和权重转换

**Comment by xidaoliang** [comment]
谢谢

**Comment by Linchunhui** [comment]
碰到了同样的问题，请问解决了吗

**Comment by xidaoliang** [comment]
可以正常转换，但是有精度损失




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tianxiaomo/pytorch-YOLOv4"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月9日(星期五) 下午3:22
收件人:&nbsp;"Tianxiaomo/pytorch-YOLOv4"<pytorch-YOLOv4@noreply.github.com&gt;;
抄送:&nbsp;"传奇"<932365660@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Tianxiaomo/pytorch-YOLOv4] 如何将训练得到的pth文件转换成weights文件 (#150)





 
碰到了同样的问题，请问解决了吗
