### ISSUE TITLE
Training on VOC datasets

### ISSUE THREAD

**Issue by zxj11838** [Tianxiaomo/pytorch-YOLOv4#157]
Does it support training on VOC dataset?  When I train, I get an error, it seems to be a problem with the dataset. Has anyone successfully trained on the VOC dataset?

**Comment by ReOneK** [comment]
no

**Comment by wenh06** [comment]
For object detection, you can inherit the class `Yolo_dataset` to produce your own data generator. The only thing you have to do is to generate `self.truth` and `self.imgs` in the correct format in the `__init__` function of your data generator. And do not forget to implement a correct `get_image_id` function.

**Comment by zhangmingjiang1114** [comment]
> For object detection, you can inherit the class `Yolo_dataset` to produce your own data generator. The only thing you have to do is to generate `self.truth` and `self.imgs` in the correct format in the `__init__` function of your data generator. And do not forget to implement a correct `get_image_id` function.
??
How to implement a correct get_image_id function?  How to modify the 'get_image_id' function?  谢谢！非常感谢！  微信：422784285
