### ISSUE TITLE
bboxes_pred of shape [m, 22743, 7] and not as expected [m, 60, 5]???

### ISSUE THREAD

**Issue by gianmarcobesso** [Tianxiaomo/pytorch-YOLOv4#160]
I am loading a pretrained model with these cfg settings:

```
 Cfg.use_darknet_cfg = True
 Cfg.cfgfile = os.path.join(_BASE_DIR, 'cfg', 'yolov4-custom.cfg')
```

I also edited the classes settings in 'yolov4-custom.cfg' from 80 to 3 ( as in my dataset). Finally this is my script to load the model and evaluate on a give dataset:

```
 ## Darknet

 model = Darknet(Cfg.cfgfile)
## Custom YOLO
#model = Yolov4(yolov4conv137weight=None, n_classes=3, inference=True)
pretrained_dict = torch.load(load_path, map_location=device)
model.load_state_dict(pretrained_dict)
model.to(device = device)
 
"Build datasets"
cfg = get_args(**Cfg)
train_dataset = Yolo_dataset(train_label, Cfg)
val_dataset = Yolo_dataset(val_label, Cfg)
test_dataset = Yolo_dataset(test_label, Cfg)

"Evaluate train set"
 train_loader = DataLoader(train_dataset, batch_size= 4, shuffle=True,
                              num_workers=0, pin_memory=True, drop_last=True, collate_fn = collate)
criterion = Yolo_loss(device = device, batch = len(train_dataset),n_classes = 3)

 with torch.no_grad():
   for i, batch in enumerate(train_loader):
       images = batch[0]
       bboxes = batch[1]
       images = images.to(device= device, dtype=torch.float32)
       bboxes = bboxes.to(device = device)
       model.eval()
       bboxes_pred = model(images)
       train_loss, train_loss_xy, train_loss_wh, train_loss_obj, train_loss_cls, train_loss_l2 = criterion(bboxes_pred, bboxes)
       print(train_loss)
```

I don't understand why the shape of bboxes_pred is [4, 22743,7] ?? Can someone help me out?

**Comment by ersheng-ai** [comment]
How many classes does this pretrained model have? 3 or 80?

**Comment by gianmarcobesso** [comment]
I changed the number of classes in cfg.py, so I believe 3. Or are the number of classes hard coded somewhere else?

**Comment by ersheng-ai** [comment]
You cannot change classes of pretrained model directly.
You have to re-design class definitions, label files and final conv layers, and then retrain the model.

**Comment by gianmarcobesso** [comment]
Yes I know that. The pretrained model was trained by me with this repository. So you are saying the changing the cfg.py is not enough to correctly train on only 3 classes? 
I thought the Yolo loss in train.py takes the correct number of classes out of cfg.py

**Comment by gianmarcobesso** [comment]
> You cannot change classes of pretrained model directly.
> You have to re-design label files, loss definitions and final convolution layers, and then retrain or fine tune the model.

Yes I know that. The pretrained model was trained by me with this repository. So you are saying the changing the cfg.py is not enough to correctly train on only 3 classes?
I thought the Yolo loss in train.py takes the correct number of classes out of cfg.py

**Comment by ersheng-ai** [comment]
Channels of final conv layers is 255 = (4 + 1 + 80) * 3
You have to change number of output channels of the last conv layers to (4 + 1 + 3) * 3

**Comment by gianmarcobesso** [comment]
> Channels of final conv layer outputs are 255 = (4 + 1 + 80) * 3
> You have to change number of output channels of the last conv layers to (4 + 1 + 3) * 3

Thank you! Is it enough to change the output channels in yolov4-custom.cfg file?

**Comment by gianmarcobesso** [comment]
> Channels of final conv layer outputs are 255 = (4 + 1 + 80) * 3
> You have to change number of output channels of the last conv layers to (4 + 1 + 3) * 3

I am still trying to fix the issue. What should be the shape of the output that is given into the function Yolo_loss?
I am getting the error: 

> 
  File "C:\Users\gianm\Documents\TU_Darmstadt\M_Sc\3_Semester\DLAM\Projekt\face-mask-detection\pytorch-YOLOv4-master\train.py", line 195, in forward
    fsize = output.shape[2]

IndexError: tuple index out of range

Maybe you can help me out.
