### ISSUE TITLE
With torch.no_grad() to improve inference time?

### ISSUE THREAD

**Issue by fabiozappo** [Tianxiaomo/pytorch-YOLOv4#162]
In models.py code, I simply changed : 

for i in range(2): 
        boxes = do_detect(model, sized, 0.4, 0.6, use_cuda)

in:
with torch.no_grad():
       for i in range(2): 
                  boxes = do_detect(model, sized, 0.4, 0.6, use_cuda)

And inference time gets really better, is there a reason why you don't set all the requires_grad flag to false?

**Comment by Tianxiaomo** [comment]
In model.py, just a simple verification, just for reference.
