### ISSUE TITLE
demo_trt.py ERROR

### ISSUE THREAD

**Issue by bjthemost** [Tianxiaomo/pytorch-YOLOv4#166]
oot@znx0pc:/opt/gits/pytorch-YOLOv4# python demo_trt.py /opt/gits/pytorch-YOLOv4/yolov4_1_3_608_608.onnx 19451.jpg 
Reading engine from file /opt/gits/pytorch-YOLOv4/yolov4_1_3_608_608.onnx
[TensorRT] ERROR: coreReadArchive.cpp (31) - Serialization Error in verifyHeader: 0 (Magic tag does not match)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "demo_trt.py", line 192, in <module>
    main(engine_path, image_path, image_size)
  File "demo_trt.py", line 114, in main
    with get_engine(engine_path) as engine, engine.create_execution_context() as context:
AttributeError: __enter__

**Comment by ersheng-ai** [comment]
Tell me your pytorch version  and tensorRT version

**Comment by nanshenwei** [comment]
same issue. pytorch==1.6 TensorRT==7.1.3.4

**Comment by ersheng-ai** [comment]
> oot@znx0pc:/opt/gits/pytorch-YOLOv4# python demo_trt.py /opt/gits/pytorch-YOLOv4/yolov4_1_3_608_608.onnx 19451.jpg
> Reading engine from file /opt/gits/pytorch-YOLOv4/yolov4_1_3_608_608.onnx
> [TensorRT] ERROR: coreReadArchive.cpp (31) - Serialization Error in verifyHeader: 0 (Magic tag does not match)
> [TensorRT] ERROR: INVALID_STATE: std::exception
> [TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
> Traceback (most recent call last):
> File "demo_trt.py", line 192, in
> main(engine_path, image_path, image_size)
> File "demo_trt.py", line 114, in main
> with get_engine(engine_path) as engine, engine.create_execution_context() as context:
> AttributeError: **enter**

`yolov4_1_3_608_608.onnx` does not look like a TensorRT engine. Use engine file like yolov4_1_3_608_608.engine to run trt demo.
