### ISSUE TITLE
train.py下的Yolo_loss是YOlO V4版本的吗？

### ISSUE THREAD

**Issue by xiajinbiao** [Tianxiaomo/pytorch-YOLOv4#169]
loss_xy += F.binary_cross_entropy(input=output[..., :2], target=target[..., :2],
                                              weight=tgt_scale * tgt_scale, size_average=False)
            loss_wh += F.mse_loss(input=output[..., 2:4], target=target[..., 2:4], size_average=False) / 2
            loss_obj += F.binary_cross_entropy(input=output[..., 4], target=target[..., 4], size_average=False)
            loss_cls += F.binary_cross_entropy(input=output[..., 5:], target=target[..., 5:], size_average=False)
            loss_l2 += F.mse_loss(input=output, target=target, size_average=False)

上面这段代码是Yolo_loss中的方法。这里并没有用到IOUloss。

           anchor_ious_all = bboxes_iou(truth_box.cpu(), self.ref_anchors[output_id], CIoU=True)

这是在对anchor筛选的时候倒是用到了GIoU。

请问GIoU不应该出现在loss计算里面吗？

**Comment by xiexie123** [comment]
+1
