### ISSUE TITLE
dataset.py -- line102

### ISSUE THREAD

**Issue by liguojun92** [Tianxiaomo/pytorch-YOLOv4#173]
bboxes = bboxes[np.where((bboxes[:, 4] < classes) & (bboxes[:, 4] >= 0))[0]]
这里为什么要用(bboxes[:, 4] < classes) & (bboxes[:, 4] >= 0)来筛选？bboxes[:]保存了所有的bbox，每一行都保存了bbox的信息，255 = 85 * 3 ，即每一行包含3个bbox，每个bbox是 85个数据，即[x1,y1,x2,y2,c,class_1...class_n]，那bboxes[:4]就是某一bbox是否检测到物体的置信度，检测到就是 1 ，否则就是0。
以上是基于yolov3的理解
但这里使用 bboxes[:4]作为筛选条件，应该怎么理解？望大神指点，不胜感激！

**Comment by liguojun92** [comment]
建议做一个说明文档 各函数的作用 参数的意义 关键性代码的注解

**Comment by Tianxiaomo** [comment]
首先对代码没有注释所带来的困扰感到抱歉，

关于

https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/fa60ecf7421fab85e552b9e00e869cf4ff077d33/dataset.py#L74

是由于box格式是[x1,y1,x2,x2,class],在cfg.py有说明

https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/fa60ecf7421fab85e552b9e00e869cf4ff077d33/cfg.py#L61

在计算loss时，会把class转换成one-hot格式，

https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/fa60ecf7421fab85e552b9e00e869cf4ff077d33/train.py#L231
