### ISSUE TITLE
Correct labels / loss_l2 loss is nan

### ISSUE THREAD

**Issue by netzkriecher** [Tianxiaomo/pytorch-YOLOv4#177]
I am trying to get this repository working for a dataset with 3 different classes. I am using Darknet and the yolov4-custom.cfg with `filters=24` in the last convolution before every YOLO layer and `classes =3` in the YOLO layer itself. Also, the cfg.py is updated for 3 classes. 

First I labeled the data as the tools/coco_annotation suggests with `x_min, y_min, x_max, y_max, class_label`. I got similar results as other people with the problem that loss_xy and loss_wh are not really improving:
![loss](https://user-images.githubusercontent.com/54553001/88057724-c32d9780-cb62-11ea-90b7-a33a57ead405.jpeg)

After printing the bounding boxes of my training data I am pretty sure you are using `x_min, y_min, width, height, class_label` in the evaluation. But after trying to train my network on these labels and printing parts of the inner loop of the Yolo_loss.forward I get nan from loss_wh and loss_l2 in some YoloHeads (mostly 2. and 3.):

```
 YOLOLayer output shape: torch.Size([1, 24, 76, 76]) 
loss_wh: tensor(0., grad_fn=<AddBackward0>) 
loss_l2: tensor(4105.4248, grad_fn=<AddBackward0>)
 YOLOLayer output shape: torch.Size([1, 24, 38, 38])
loss_w:h tensor(0., grad_fn=<AddBackward0>)
loss_l2: tensor(5269.9297, grad_fn=<AddBackward0>)
 YOLOLayer output shape: torch.Size([1, 24, 19, 19])
loss_wh: tensor(nan, grad_fn=<AddBackward0>)
loss_l2: tensor(nan, grad_fn=<AddBackward0>)
```

And also an Error for the loss_xy in some iterations:

```
line 2378, in binary_cross_entropy
    return torch._C._nn.binary_cross_entropy(
RuntimeError: all elements of input should be between 0 and 1
```
When I set the parameter `xyxy=False` in bboxes_iou during training with the x,y,w,h label format I just get nans for loss_wh and loss_l2 as output in all Yololayers.

**Comment by netzkriecher** [comment]
Problem solved: I used the ReduceLROnPlateau scheduler before. The learning rate was reduced way too early which resolved in the network not learning properly. Instead, I now use the same scheduler as the default one in the repository (with the burn-in schedule). Also using the smaller pre-trained model helped as well.

**Comment by LIUhansen** [comment]
I also meet same problem. How to use  ReduceLROnPlateau scheduler?

**Comment by Fee532** [comment]
2021-01-30 21:29:26,210 x2num.py[line:14] WARNING: NaN or Inf found in input tensor.
2021-01-30 21:29:26,211 x2num.py[line:14] WARNING: NaN or Inf found in input tensor.
2021-01-30 21:29:26,212 x2num.py[line:14] WARNING: NaN or Inf found in input tensor.
2021-01-30 21:29:26,228 train.py[line:417] DEBUG: Train step_640: loss : nan,loss xy : 1141.13232421875,loss wh : nan,loss obj : 524.9893798828125，loss cls : 524.9893798828125,loss l2 : nan,lr : 1e-05

my problem.
try:
 scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='max', verbose=True, patience=6, min_lr=1e-7)
but  useless

**Comment by sakumashirayuki** [comment]
I also trained the model on my custom dataset and I use the default scheduler. The wh loss was always nan. I have tried to change the xyxy=False to xyxy=True, but it didn't work.
