### ISSUE TITLE
your training files (train.txt and val.txt)

### ISSUE THREAD

**Issue by love2learn-7179** [Tianxiaomo/pytorch-YOLOv4#18]
First, thank you so much for your great work.
I am currently trying to learn YOLOv4 using your implementation.
I am interested in training. 
Can you share your train.txt and val.txt for me to reproduce your work?
Cfg.train_label = 'data/train.txt'
Cfg.val_label = 'data/val.txt'

Thanks!!

**Comment by Tianxiaomo** [comment]
You can use tool/coco_annotation.py  to generate train.txt and val.txt, their formats are also described in cfg.py

**Comment by love2learn-7179** [comment]
thank you so much :)
