### ISSUE TITLE
What is the output format?

### ISSUE THREAD

**Issue by betaarnsburg** [Tianxiaomo/pytorch-YOLOv4#180]
Thank you for your repo! But I wonder what the output format is?
For my custom datasets, the input lables format: image_path x1_min,y1_min,x1_max,y1_max,class x2_min,y2_min,x2_max,y2_max,class  ....

But how about the output format? like: image_path confidence,x1_min,y1_min,x1_max,y1_max,class ... 
Am I right?
Looking forward to your reply.

**Comment by ersheng-ai** [comment]
[README.md](https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/master/README.md) tells you inference output format.

**Comment by sumanthratna** [comment]
https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/master/README.md#24-inference-output has the inference output, but what is the format of the output during training (`inference = False`)? The output of the model is a Python list with the following shapes: `[(1, 21, 32, 32), (1, 21, 16, 16), (1, 21, 8, 8)]`. 

I want to draw the training outputs onto the original image, as if it was inference.
