### ISSUE TITLE
Predictions and labels box format in YoloLoss forward method

### ISSUE THREAD

**Issue by danilopeixoto** [Tianxiaomo/pytorch-YOLOv4#187]
Do the boxes of the `labels` parameter in the `YoloLoss` forward method have normalized coordinates as the predictions parameter (`xin`)?

```python
def forward(self, xin, labels=None)
```

**Comment by kirillfish** [comment]
Please, explain how you solved this problem. I'm facing it too, and it's ambiguous. Seems that original weights work with normalized boxes, while augmentations in the training pipeline are designed for unnormalized ones.
