### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '30 #255'

### ISSUE THREAD

**Issue by bessszilard** [Tianxiaomo/pytorch-YOLOv4#189]
Hello!

Thank you for this great library! I trained the model, and I created a demo successfully with the darknet library. Based on this I guess, that .cfg and .data files are okay. I tried to convert a darknet yolov4 model to PyTorch one, and I got this error:

```bash
Traceback (most recent call last):
  File "demo.py", line 155, in <module>
    detect_cv2(args.cfgfile, args.weightfile, args.imgfile)
  File "demo.py", line 27, in detect_cv2
    m = Darknet(cfgfile)
  File "/content/pytorch-YOLOv4/tool/darknet2pytorch.py", line 144, in __init__
    self.models = self.create_network(self.blocks)  # merge conv, bn,leaky
  File "/content/pytorch-YOLOv4/tool/darknet2pytorch.py", line 254, in create_network
    filters = int(block['filters'])
ValueError: invalid literal for int() with base 10: '30 #255'
```

My cfg file: https://drive.google.com/file/d/150ow6bVbUcNcPvyh8UajDpLtgOjmr8ub/view?usp=sharing
My weights: https://drive.google.com/file/d/1-RPnDFn9_Q1z4bQKDxkcNYPoUBPAPGWT/view?usp=sharing

Library versions:
```
numpy==1.18.2
torch==1.4.0
tensorboardX==2.0
```

What causes the error?

**Comment by Stanley-Zheng** [comment]
I have the exact same issue when I try to continue training my .pth file that I converted from a darknet save. 

`  File "../input/pytorchyolov4/train.py", line 627, in <module>
    device=device, )
  File "../input/pytorchyolov4/train.py", line 292, in train
    train_dataset = Yolo_dataset(config.train_label, config, train=True)
  File "/content/input/pytorchyolov4/dataset.py", line 261, in __init__
    truth[data[0]].append([int(j) for j in i.split(',')])
  File "/content/input/pytorchyolov4/dataset.py", line 261, in <listcomp>
    truth[data[0]].append([int(j) for j in i.split(',')])
ValueError: invalid literal for int() with base 10: ''`

From my experience, it may be something to do with int("50.00") or trying to convert a string with decimals, you must do int(float("50.00")). However, I must experiment further.
