### ISSUE TITLE
How to use darknet2pytorch.py

### ISSUE THREAD

**Issue by haviduck** [Tianxiaomo/pytorch-YOLOv4#207]
Heya,
Im trying to figure out how to use the darknet2pytorch script as i want my cfg and weight file to be converted, ive tried calling Darknet, but it looks like it only takes a cfg param. When i give it a yolo4-tiny cfg it spits back "convalution havn't activate linear"
Any help is greatly appreciated :)

**Comment by Tianxiaomo** [comment]
"convalution havn't activage linear" does not affect model transformation.

**Comment by haviduck** [comment]
> "convalution havn't activage linear" does not affect model transformation.

thanks, figured it out :)
