### ISSUE TITLE
AssertionError: results do not correspond to current coco set

### ISSUE THREAD

**Issue by YuzhouPeng** [Tianxiaomo/pytorch-YOLOv4#219]
I got this error when I finished  my first training epoch, following are my error message and train.txt format(same with val.txt):

![Screenshot from 2020-08-10 10-06-52](https://user-images.githubusercontent.com/13601004/89747530-be209000-daf1-11ea-8cba-93afe8162648.png)

![Screenshot from 2020-08-10 10-07-11](https://user-images.githubusercontent.com/13601004/89747534-c24cad80-daf1-11ea-8b0e-bc4f51ae1e0a.png)

need help!

**Comment by MBocchi** [comment]
This error occurs when you have a bad implementation of the function `get_image_id`. Using global variable as ID will constantly increments your value, instead of having a specific ID for each image.

**Comment by Yachumika** [comment]
I have the same problem, when  i finished my first epoch too.

**Comment by alaap001** [comment]
> I got this error when I finished my first training epoch, following are my error message and train.txt format(same with val.txt):
> 
> ![Screenshot from 2020-08-10 10-06-52](https://user-images.githubusercontent.com/13601004/89747530-be209000-daf1-11ea-8cba-93afe8162648.png)
> 
> ![Screenshot from 2020-08-10 10-07-11](https://user-images.githubusercontent.com/13601004/89747534-c24cad80-daf1-11ea-8b0e-bc4f51ae1e0a.png)
> 
> need help!

Have you solved the issue?
