### ISSUE TITLE
How to convert from the Darknet model weights to Yolov4.pth?

### ISSUE THREAD

**Issue by love2learn-7179** [Tianxiaomo/pytorch-YOLOv4#22]
Hi, 

If I am interested in fine-tuning the yolov4 model. Is there a way I can convert from the Darknet model weights to Yolov4.pth? (any tips would be appreciated)
And, if you have, can you plz share it w/ me? 

Thank you.

**Comment by Tianxiaomo** [comment]
you can use dark2pytorch.py,this can save *.pth

**Comment by murdockhou** [comment]
@Tianxiaomo We can save *.pth right, but can not show friendly using Netron.
