### ISSUE TITLE
cv2 error

### ISSUE THREAD

**Issue by 2730gf** [Tianxiaomo/pytorch-YOLOv4#228]
This bug occurred when training with coco. The format of train.txt was converted by using COCO_annotation. py, so the format should be no problem.

What's the problem? Can you help me

2020-08-14 17:22:25,905 train.py[line:616] INFO: Using device cuda
convalution havn't activate linear
convalution havn't activate linear
convalution havn't activate linear
2020-08-14 17:22:32,364 train.py[line:327] INFO: Starting training:
        Epochs:          300
        Batch size:      64
        Subdivisions:    16
        Learning rate:   0.001
        Training size:   82081
        Validation size: 40137
        Checkpoints:     True
        Device:          cuda
        Images size:     608
        Optimizer:       adam
        Dataset classes: 80
        Train label path:/home/workspace/gongfu/target_detection/yolov4/pytorch-YOLOv4/data/train.txt
        Pretrained:
    
Epoch 1/300:   0%|     | 0/82081 [00:00<?, ?img/s]
Traceback (most recent call last):
  File "train.py", line 631, in <module>
    device=device, )
  File "train.py", line 370, in train
    for i, batch in enumerate(train_loader):
  File "/home/workspace/gongfu/anaconda3/envs/yolov4/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/workspace/gongfu/anaconda3/envs/yolov4/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/workspace/gongfu/anaconda3/envs/yolov4/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/workspace/gongfu/anaconda3/envs/yolov4/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/workspace/gongfu/anaconda3/envs/yolov4/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/workspace/gongfu/anaconda3/envs/yolov4/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/workspace/gongfu/anaconda3/envs/yolov4/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/workspace/gongfu/target_detection/yolov4/pytorch-YOLOv4/dataset.py", line 297, in __getitem__
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(3.4.9) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by 924175302** [comment]
I have the same problem as you, have you solved it @2730gf

**Comment by kanybekasanbekov** [comment]
Most probably you gave wrong `img_path` in `img = cv2.imread(img_path)`. Since you were not able to load an image, you cannot convert from BGR to RGB

**Comment by mei123456789** [comment]
> This bug occurred when training with coco. The format of train.txt was converted by using COCO_annotation. py, so the format should be no problem.
> 
> What's the problem? Can you help me
> 
> 2020-08-14 17:22:25,905 train.py[line:616] INFO: Using device cuda convalution havn't activate linear convalution havn't activate linear convalution havn't activate linear 2020-08-14 17:22:32,364 train.py[line:327] INFO: Starting training: Epochs: 300 Batch size: 64 Subdivisions: 16 Learning rate: 0.001 Training size: 82081 Validation size: 40137 Checkpoints: True Device: cuda Images size: 608 Optimizer: adam Dataset classes: 80 Train label path:/home/workspace/gongfu/target_detection/yolov4/pytorch-YOLOv4/data/train.txt Pretrained:
> 
> Epoch 1/300: 0%| | 0/82081 [00:00<?, ?img/s] Traceback (most recent call last): File "train.py", line 631, in device=device, ) File "train.py", line 370, in train for i, batch in enumerate(train_loader): File "/home/workspace/gongfu/anaconda3/envs/yolov4/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in **next** data = self._next_data() File "/home/workspace/gongfu/anaconda3/envs/yolov4/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data return self._process_data(data) File "/home/workspace/gongfu/anaconda3/envs/yolov4/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data data.reraise() File "/home/workspace/gongfu/anaconda3/envs/yolov4/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise raise self.exc_type(msg) cv2.error: Caught error in DataLoader worker process 0. Original Traceback (most recent call last): File "/home/workspace/gongfu/anaconda3/envs/yolov4/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop data = fetcher.fetch(index) File "/home/workspace/gongfu/anaconda3/envs/yolov4/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/workspace/gongfu/anaconda3/envs/yolov4/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/workspace/gongfu/target_detection/yolov4/pytorch-YOLOv4/dataset.py", line 297, in **getitem** img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) cv2.error: OpenCV(3.4.9) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

你好，请问你解决了嘛？我也遇到了同样的问题，需要你的帮助，非常感谢
