### ISSUE TITLE
difference between models in darknet2pytorch.py and models.py ?

### ISSUE THREAD

**Issue by yuxx0218** [Tianxiaomo/pytorch-YOLOv4#243]
if cfg.use_darknet_cfg:
        model = Darknet(cfg.cfgfile)
 else:
        model = Yolov4(cfg.pretrained, n_classes=cfg.classes)

**Comment by ersheng-ai** [comment]
`darknet2pytorch.py` transforms darknet model into pytorch.
`models.py` implement a pytorch model independently.
