### ISSUE TITLE
There is something wrong in loading dataset when training my own dataset.

### ISSUE THREAD

**Issue by LJC-GitHub** [Tianxiaomo/pytorch-YOLOv4#25]
File "F:/PYTHON_project/pytorch-YOLOv4/dataset.py", line 375, in __getitem__
    cut_y, i, left_shift, right_shift, top_shift, bot_shift)
  File "F:/PYTHON_project/pytorch-YOLOv4/dataset.py", line 215, in blend_truth_mosaic
    bboxes = filter_truth(bboxes, left_shift, top_shift, cut_x, cut_y, 0, 0)
  File "F:/PYTHON_project/pytorch-YOLOv4/dataset.py", line 184, in filter_truth
    bboxes[:, 0] -= dx
IndexError: too many indices for array

Who has solved such a problem?Can you tell me?Thank you!

**Comment by lifei1229** [comment]
我也需要这个问题：
![image](https://user-images.githubusercontent.com/15320628/82120241-41fb0280-97b7-11ea-8760-aaa1e4eb0a46.png)

**Comment by lifei1229** [comment]
> File "F:/PYTHON_project/pytorch-YOLOv4/dataset.py", line 375, in **getitem**
> cut_y, i, left_shift, right_shift, top_shift, bot_shift)
> File "F:/PYTHON_project/pytorch-YOLOv4/dataset.py", line 215, in blend_truth_mosaic
> bboxes = filter_truth(bboxes, left_shift, top_shift, cut_x, cut_y, 0, 0)
> File "F:/PYTHON_project/pytorch-YOLOv4/dataset.py", line 184, in filter_truth
> bboxes[:, 0] -= dx
> IndexError: too many indices for array
> 
> Who has solved such a problem?Can you tell me?Thank you!

**Comment by Tianxiaomo** [comment]
Sorry, I haven't seen issues for a long time. Is this issue still on.
@lifei1229 @LJC-GitHub

**Comment by Hidayat722** [comment]
Same problem did any one solved it.

**Comment by zhaowenyi7** [comment]
这个问题是因为有些图片当中没有任何一个类别的目标，标注文件train.txt中对于这张图片只有名字而没有box信息，就会导致bboxes索引不正常，不能进行boardcast
我现在的解决办法是不在train.txt中写入无目标的图片
