### ISSUE TITLE
Some mistakes

### ISSUE THREAD

**Issue by WZTENG** [Tianxiaomo/pytorch-YOLOv4#27]
首先感谢兄弟的代码。
models.py 里面的代码：论文写的是Neck，不是Neek
/tool/ 文件夹下是不是少的了一个字母：coco_annotatin.py -> coco_annotation.py ???
dataset.py 中数据集有少部分生成数据的值会大于255，这是允许的嘛？在rgb转hsv增强后再转回rgb时产生的，这是预期的情况嘛？
train.py 中val_loader实例少写了collate_fn在enumerate(val_loader)时会报错。

===Google Translate===
First of all thanks to the brothers for the code.
Code in models.py: The paper is written for Neck, not Neek
Is there a letter missing in the / tool / folder: coco_annotatin.py-> coco_annotation.py ???
A small part of the data set in dataset.py will have a value greater than 255. Is this allowed? It is generated when rgb is converted to hsv and then back to rgb. Is this the expected situation?
The val_loader instance in train.py is less written. collate_fn will report an error when enumerate (val_loader).

**Comment by VCasecnikovs** [comment]
Hello, worth to mention, that in dataset You are using cutmix technic, but not mixup.

**Comment by Tianxiaomo** [comment]
@WZTENG 
是的，名字打错了，后面也忘改了（手动狗头）
@VCasecnikovs 
Emmm,I think it should be mixup and mosaic,but not cutmix.w(ﾟДﾟ)w

**Comment by WZTENG** [comment]
@VCasecnikovs thanks
