### ISSUE TITLE
Do you mind inviting me to development of your repository?

### ISSUE THREAD

**Issue by ersheng-ai** [Tianxiaomo/pytorch-YOLOv4#30]
I think you have already contributed a lot into the opensource community on behalf of YOLOv4.
But I think we'd better en-tighten relations between your repository and the ONNX standard. This would also contribute to popularity of your repository .

I will add some python scripts here:
1. A script to convert pytorch into ONNX
2. An inference demo running ONNX

**Comment by Tianxiaomo** [comment]
> I think you have already contributed a lot into the opensource community on behalf of YOLOv4.
> But I think we'd better en-tighten relations between your repository and the ONNX standard. This would also contribute to popularity of your repository .
> 
> I will add some python scripts here:
> 
> 1. A script to convert pytorch into ONNX
> 2. An inference demo running ONNX

Welcome aboard.

**Comment by ersheng-ai** [comment]
I am ready to push my part of code.
Please invite me to the contributors.

**Comment by Tianxiaomo** [comment]
already invited.
