### ISSUE TITLE
在evaluate的时候卡住了

### ISSUE THREAD

**Issue by oyange** [Tianxiaomo/pytorch-YOLOv4#306]
![image](https://user-images.githubusercontent.com/23448269/96977199-53f38500-154f-11eb-8358-8683ec420518.png)
如上图所示，在这里卡住了，
在这里进不去循环，感觉很奇怪for images, targets in data_loader:

**Comment by xwq-jfl** [comment]
我也是这样的，求解答

**Comment by sunshine-zkf** [comment]
出现同样的问题

**Comment by zzzbzzz** [comment]
Try setting num_workers as 0 in DataLoader.

**Comment by oyange** [comment]
解决了num_workers设置为0，但是这样会很慢

**Comment by oyange** [comment]
换了yolov5的模型，但是仍然出现了类似的问题，把共享内存增大就ok了
