### ISSUE TITLE
self.anchors  in Yolo_loss (in train.py) is different from the one from yolov4.cfg or the one from do_detect().

### ISSUE THREAD

**Issue by love2learn-7179** [Tianxiaomo/pytorch-YOLOv4#31]
The values of anchors in Yolo_loss seem different from the others (from yolov4.cfg and do_detect()).
It seems like it's from yolov3.cfg. 
Can you plz double check on this, if it's not intended?

Thank you:)

**Comment by Tianxiaomo** [comment]
sorry, I was careless
