### ISSUE TITLE
训练第一个epoch，提示如下错误

### ISSUE THREAD

**Issue by sangwz** [Tianxiaomo/pytorch-YOLOv4#341]
![torchFault](https://user-images.githubusercontent.com/58506571/101238262-05263700-371a-11eb-96dc-096294b141cb.png)

错误是opencv未读取到内容。是将代码clone到本地，然后使用作者的硬币数据集做的测试。有了解错误原因的吗？不胜感激

**Comment by futureflsl** [comment]
你先跑跑预训练模型看看，根本检测不出来，我都换2个电脑了。而且训练的模型也不能用

**Comment by sangwz** [comment]
> 你先跑跑预训练模型看看，根本检测不出来，我都换2个电脑了。而且训练的模型也不能用

**Comment by sangwz** [comment]
> 你先跑跑预训练模型看看，根本检测不出来，我都换2个电脑了。而且训练的模型也不能用

**Comment by WanyueZhao** [comment]
楼主有碰到这个错误吗？ValueError: need at least one array to concatenate

**Comment by kenait1224** [comment]
這個問題是因為` dataset.py` 沒有讀到正確路徑的圖而導致，請確認你的` train.txt `指向正確的路徑（建議使用絕對路徑），如果你也與我一樣是使用`coco_annotation.py` 由coco轉換為txt檔案的話，請將`coco_annotation.py`檔案中的第34行`  name = os.path.join(images_dir_path, images[id]['file_name'])`取代第35行`name = os.path.join(images_dir_path, '{:012d}.jpg'.format(id))`以確保檔案名稱相同。

**Comment by mei123456789** [comment]
> 這個問題是因為` dataset.py` 沒有讀到正確路徑的圖而導致，請確認你的`train.txt`指向正確的路徑（建議使用絕對路徑），如果你也與我一樣是使用`coco_annotation.py` 由coco轉換為txt檔案的話，請將`coco_annotation.py`檔案中的第34行` name = os.path.join(images_dir_path, images[id]['file_name'])`取代第35行`name = os.path.join(images_dir_path, '{:012d}.jpg'.format(id))`以確保檔案名稱相同。

你好，我也遇到了同样的问题但是按你的方法出现越界现象，怎么处理呀

**Comment by mei123456789** [comment]
> ![torchFault](https://user-images.githubusercontent.com/58506571/101238262-05263700-371a-11eb-96dc-096294b141cb.png)
> 
> 错误是opencv未读取到内容。是将代码clone到本地，然后使用作者的硬币数据集做的测试。有了解错误原因的吗？不胜感激

你好，请问你解决了么？可否帮助我一下，我也遇到了同样的错误
