### ISSUE TITLE
数据集必须是您实验中要求的数据格式嘛，自己用LabelImg标注的数据集可以吗@Tianxiaomo

### ISSUE THREAD

**Issue by shuang1204** [Tianxiaomo/pytorch-YOLOv4#348]

**Comment by snowyseaons** [comment]
参考这个数据集格式就可以
https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/master/Use_yolov4_to_train_your_own_data.md

**Comment by Tianxiaomo** [comment]
修改dataset，想用什么格式用什麽格式
