### ISSUE TITLE
How to use the pytorch model?

### ISSUE THREAD

**Issue by MRGAO1996** [Tianxiaomo/pytorch-YOLOv4#36]
I want to use the .pth file alone without .weights file, what should I do?
Thank you so much.

**Comment by vkrd** [comment]
If you use the --load argument when calling train.py, then you can just pass the location of your model.pth

**Comment by Tianxiaomo** [comment]
you can refer to models.py
```
if __name__ == "__main__":
    model = Yolov4()

    pretrained_dict = torch.load('weight/yolov4.pth')
    model.load_state_dict(pretrained_dict)

    num_classes = 80
    if num_classes == 20:
        namesfile = 'data/voc.names'
    elif num_classes == 80:
        namesfile = 'data/coco.names'
    else:
        namesfile = 'data/names'

    use_cuda = 0
    if use_cuda:
        model.cuda()

    from PIL import Image

    img = Image.open("data/dog.jpg").convert('RGB')
    sized = img.resize((608, 608))
    from tool.utils import *

    boxes = do_detect(model, sized, 0.5, 0.4, use_cuda)

    class_names = load_class_names(namesfile)
    plot_boxes(img, boxes, 'predictions.jpg', class_names)
```

**Comment by vkrd** [comment]
Or use @Tianxiaomo's answer if you want to apply the model to an image

**Comment by MRGAO1996** [comment]
> you can refer to models.py
> 
> ```
> if __name__ == "__main__":
>     model = Yolov4()
> 
>     pretrained_dict = torch.load('weight/yolov4.pth')
>     model.load_state_dict(pretrained_dict)
> 
>     num_classes = 80
>     if num_classes == 20:
>         namesfile = 'data/voc.names'
>     elif num_classes == 80:
>         namesfile = 'data/coco.names'
>     else:
>         namesfile = 'data/names'
> 
>     use_cuda = 0
>     if use_cuda:
>         model.cuda()
> 
>     from PIL import Image
> 
>     img = Image.open("data/dog.jpg").convert('RGB')
>     sized = img.resize((608, 608))
>     from tool.utils import *
> 
>     boxes = do_detect(model, sized, 0.5, 0.4, use_cuda)
> 
>     class_names = load_class_names(namesfile)
>     plot_boxes(img, boxes, 'predictions.jpg', class_names)
> ```

My bad, I only looked into 'tool', 'models.py' works. Thank you!
