### ISSUE TITLE
transfer onnx to TensorRT

### ISSUE THREAD

**Issue by illiad-tigerdhl** [Tianxiaomo/pytorch-YOLOv4#363]
I run the command：
trtexec --onnx=yolov4_1_3_512_512.onnx --explicitBatch --saveEngine=yolov4_1_3_512_512.engine --workspace=2048 --fp16

get the issue ，how can I fix it?
-bash: trtexec: command not found

**Comment by illiad-tigerdhl** [comment]
I found that the right command is to index the TensorRT install dir，and run
/usr/src/tensorrt/bin/trtexec --onnx=yolov4_1_3_512_512.onnx 。。。。。

**Comment by MoshiurRahmanFaisal** [comment]
> I run the command： trtexec --onnx=yolov4_1_3_512_512.onnx --explicitBatch --saveEngine=yolov4_1_3_512_512.engine --workspace=2048 --fp16
> 
> get the issue ，how can I fix it? -bash: trtexec: command not found

You need to build tensorrt command line wrapper: trtexec to execute trtexec command. You can follow this blog: https://medium.com/@moshiur.faisal01/install-tensorrt-with-command-line-wrapper-trtexec-on-ununtu-20-04-lts-3e44f4f36a2b

**Comment by justtools** [comment]
I also encountered the same issue, but it was resolved after I reinstalled the CUDA environment.
