### ISSUE TITLE
Giving Missing key(s) in state_dict error while making prediction on images.

### ISSUE THREAD

**Issue by vishnuvardhan58** [Tianxiaomo/pytorch-YOLOv4#365]
Hello , I have trained yolov4 using repository on my own dataset, and I am trying to make predictions on images using the weight file I have obtained after training. While make predictions I am getting the following error, can you please help in solving this error ?  @ersheng-ai  can you help me with this? 

<img width="869" alt="error" src="https://user-images.githubusercontent.com/9161539/104650395-82838680-568c-11eb-8afc-a8b750f9ee78.PNG">

**Comment by shuang1204** [comment]
您好，我也遇到了同样的问题，请问是怎么解决的呢？@vishnuvardhan58@Tianxiaomo

**Comment by zzxzxzzxz** [comment]
Hi, did you solve the problem?

**Comment by Im-JimmyHu** [comment]
Hi, did you solve the problem?
