### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by vishnuvardhan58** [Tianxiaomo/pytorch-YOLOv4#367]
Hello , when I am trying to train using my own dataset , I am getting the following error shown below , please help me in resoving this 

! python train.py -l 0.001 -g 0 -pretrained ./yolov4.conv.137.pth -classes 80 -dir ./train -train_label_path ./train/train.txt

<img width="672" alt="error" src="https://user-images.githubusercontent.com/9161539/104850927-4b011e00-58c8-11eb-9059-2b0dcc0c0210.PNG">

**Comment by snowyseaons** [comment]
Modify the code of function 'get_image_id' which is in dataset.py according to your dataset.
