### ISSUE TITLE
Residual over dense?

### ISSUE THREAD

**Issue by VCasecnikovs** [Tianxiaomo/pytorch-YOLOv4#37]
Hello, I've read your code and I managed to find some things, where refactoring is needed and which are not as in official yolo network. The first one downsamples from DownSample 2 to DownSample 5 are the same code, I offer you to use one module to all of them, the CSP in network is nice. Second, I have not found DENSENET layer in your implementation, it should be between downsampling and SPP. I hope we will find the way of dealing with this problem.
Best regards,
Vadim.

**Comment by Tianxiaomo** [comment]
I just built the network according to yolov4.cfg.

![UTOOLS1590071623107.png](https://user-gold-cdn.xitu.io/2020/5/21/17237a782679cf4d?w=299&h=218&f=png&s=77882)

**Comment by Arvin1201** [comment]
I read your code. Your code is completely implemented according to the official author yolov4.cfg
