### ISSUE TITLE
None of the objects are detected

### ISSUE THREAD

**Issue by kimtaehyeong** [Tianxiaomo/pytorch-YOLOv4#400]
Hi.
I downloaded the weight according to the manual and executed it with the following command.
"""
python demo.py -cfgfile cfg/yolov4.cfg -weightfile models/yolov4.pth -imgfile data/dog.jpg
"""

However, a phenomenon that cannot be detected occurred.

"""
Loading weights from models/yolov4.pth... Done!
-----------------------------------
           Preprocess : 0.000998
      Model Inference : 2.742665
-----------------------------------
-----------------------------------
bboxes_batch: [[]]
       max and argmax : 0.002992
                  nms : 0.000997
Post processing total : 0.003989
-----------------------------------
-----------------------------------
           Preprocess : 0.000998
      Model Inference : 2.771589
-----------------------------------
-----------------------------------
bboxes_batch: [[]]
       max and argmax : 0.002993
                  nms : 0.000997
Post processing total : 0.003990
-----------------------------------
data/dog.jpg: Predicted in 2.913210 seconds.
save plot results to predictions.jpg
"""

How can I fix it?
I wonder if it is using cpu.

Thank you.

**Comment by kimtaehyeong** [comment]
i solved it weight load...

**Comment by Clearlove4396** [comment]
hi, I have also encountered this problem. Could you share your solution in detail？

**Comment by RuochenQi** [comment]
same problem, @Clearlove4396  did you solve it? many thanks.

**Comment by RuochenQi** [comment]
solved, weightfile should be .weight instead of .pth file.
Thank you all the same!!
