### ISSUE TITLE
Critical Typo in code

### ISSUE THREAD

**Issue by Anakin100100** [Tianxiaomo/pytorch-YOLOv4#406]
There is an obvoius typo somewhere in your code where you wrote "neek" instead of "neck" in part where it loads the state dictionary. 

Converting to onnx and running demo ...
Traceback (most recent call last):
  File "/content/pytorch-YOLOv4/demo_pytorch2onnx.py", line 96, in <module>
    main(weight_file, image_path, batch_size, n_classes, IN_IMAGE_H, IN_IMAGE_W)
  File "/content/pytorch-YOLOv4/demo_pytorch2onnx.py", line 72, in main
    transform_to_onnx(weight_file, batch_size, n_classes, IN_IMAGE_H, IN_IMAGE_W)
  File "/content/pytorch-YOLOv4/demo_pytorch2onnx.py", line 20, in transform_to_onnx
    model.load_state_dict(pretrained_dict)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Yolov4:
      Missing key(s) in state_dict: "neek.conv1.conv.0.weight", "neek.conv1.conv.1.weight", "neek.conv1.conv.1.bias" ...
      Unexpected key(s) in state_dict: "neck.conv1.conv.0.weight", "neck.conv1.conv.1.weight", "neck.conv1.conv.1.bias" ...

Please fix it fast because I really need to transform this model to onnx.

**Comment by ktro2828** [comment]
@Anakin100100 this is a one of the way to  fix it

```python: rewrite_weight.py
#!/usr/bin/env python
import torch


def rewrite(model, weight_path, ouput_path):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")   
    weight = torch.load(weight_path , map_location=device)
    
    weight_dict = {}
    for key, val in weight.items():
        if 'neek' in the key:
            key = key.replace("neek", "neck")
        weight_dict.update({key: val})
    model.load_state_dict(weight_dict)
    torch.save(model.state_dict(), output_path)
```

**Comment by Anakin100100** [comment]
@ktro2828  thank you for your response. Could you elaborate further what could have been the cause of this unusual issue?

**Comment by ktro2828** [comment]
@Anakin100100 I think the cause is typo in the definition of model [in `models.py`](https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/4ccef0ec8fe984e059378813e33b3740929e0c19/models.py#L422)

so if you define instance of `Neck()` as `neck`, not `neek`, get keyerror

**Comment by Anakin100100** [comment]
@ktro2828 this is very odd as I haven't accessed the model manually but through import, so there was no possibility for me to have changed it by accident. I imported the model from the cloned repo of Yolov4 in Pytorch from Roboflow which seems to be a fork of your repo from some time ago. But there is no typo there nor in your code.
