### ISSUE TITLE
model training issue // 训练模型出错！ 求助！！ 

### ISSUE THREAD

**Issue by lr13953301387** [Tianxiaomo/pytorch-YOLOv4#421]
Hi, 
I train to train the model on my dataset, other parts work fine but when it starts training, it raises an error, "shape '[4, 3, 8, 76, 76]' is invalid for the input of size 5891520.  Does anyone know what might cause this error?

**Comment by lr13953301387** [comment]
Epoch 1/20:   0%|         | 0/25 [00:56<?, ?img/s]
Traceback (most recent call last):
  File "train.py", line 612, in <module>
    device=device, )
  File "train.py", line 366, in train
    loss, loss_xy, loss_wh, loss_obj, loss_cls, loss_l2 = criterion(bboxes_pred, bboxes)
  File "D:\python37\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "train.py", line 228, in forward
    output = output.view(batchsize, self.n_anchors, n_ch, fsize, fsize)
RuntimeError: shape '[4, 3, 8, 76, 76]' is invalid for input of size 5891520

**Comment by lr13953301387** [comment]
打算跑作者 识别硬币那个例子然后报了上面的错误。有人知道为啥不啦？

**Comment by lr13953301387** [comment]
打算用这个模型跑自己数据然后报了上面的错误，有人知道为啥不啦？ 跑作者的硬币图片也报错

**Comment by zzxzxzzxz** [comment]
Maybe this
https://github.com/Tianxiaomo/pytorch-YOLOv4/issues/138#issuecomment-721116468

**Comment by LeBron-Jian** [comment]
I also encountered the same problem, my solution is update the following methods:

Cfg.use_darknet_cfg = False
 Cfg.cfgfile = 'cfg/yolov4.cfg' 

maybe you can update the cfg/yolov4.cfg if you use the darknet cfg ,link is https://github.com/Tianxiaomo/pytorch-YOLOv4/issues/421#issuecomment-823884520

**Comment by Richsheep** [comment]
问题大概率在于cfg文件与输入类别不匹配
@zzxzxzzxz 给出的链接与你的问题相同，如果那个issue不能解决你的问题
你可以把你的cfg.py以及cfg/yolov4.cfg发上来详细确认
