### ISSUE TITLE
Typo in the name of  Yolov4 class member representing Neck

### ISSUE THREAD

**Issue by MekhailS** [Tianxiaomo/pytorch-YOLOv4#445]
https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/4ccef0ec8fe984e059378813e33b3740929e0c19/models.py#L422

As it seems to be, there is a typo in member's name "neck"

**Comment by Abdulaaty** [comment]
@Tianxiaomo 
The weights saved have the layers name of "neek" instead of renamed "neck". You might want to update the weights available for download

**Comment by GeorgeTsio** [comment]
> @Tianxiaomo The weights saved have the layers name of "neek" instead of renamed "neck". You might want to update the weights available for download

How to solve that?
