### ISSUE TITLE
There is a problem with line 102 in the training file: “i” is not defined

### ISSUE THREAD

**Issue by Arvin1201** [Tianxiaomo/pytorch-YOLOv4#46]
it is recommended to modify it as follows: put the following code into the for loop
all_anchors_grid = [(self.anchors[mask][0] / self.strides[i], self.anchors[mask][1] / self.strides[i]) for mask in self.anch_masks[i]]

**Comment by Tianxiaomo** [comment]
I saw someone submit request in the morning, I merged directly, no validation.

my fault.

Modified.

**Comment by Arvin1201** [comment]
Even if you put it directly in the for loop, it's easy to get the illusion. When it's used for detection, there are only three anchors on each feature layer, but the misunderstanding your code may cause is that there are nine anchors
So my personal advice is to write like this：

all_anchors_grid = [(self.anchors[mask][0] / self.strides[i], self.anchors[mask][1] / self.strides[i]) for mask in self.anch_masks[i]]
 just my  personal suggestion 
haha……
