### ISSUE TITLE
Can Only Achieve 26% AP with 608x608 on MSCOCO 2017?

### ISSUE THREAD

**Issue by jielyu** [Tianxiaomo/pytorch-YOLOv4#489]
Can Only achieve 26% AP with 608x608 on MSCOCO 2017?

But the paper says, it can achieve 43% AP with 608x608.

**Comment by XuecWu** [comment]
请问您训练训练了多少个epoch？

**Comment by jielyu** [comment]
@XuecWu 50个epoch左右就基本收敛了，再训练下去就开始过拟合了

**Comment by XuecWu** [comment]
@jielyu  啊这，我现在还正在训练，我看YOLOX那些都得训练300个epoch，你超参数设定是啥啊兄弟，我是只加载主干权重训练，冰冻主干学习率为0.00125，不冰冻为0.000125，bs都是64

**Comment by jielyu** [comment]
@XuecWu 参数基本没有修改，按照这份代码跑的。一般是要训将近300epoch，但是才训到50就开始过拟合就不太对劲，所以停了。yolox初步试了一下，比较简单，损失下降也挺明显，没有训练到收敛就先停了，先学习一下损失函数的设计

**Comment by XuecWu** [comment]
@jielyu 训练到50个epoch拟合就离谱，太玄乎了==
