### ISSUE TITLE
-dir 参数问题

### ISSUE THREAD

**Issue by zhxcumt** [Tianxiaomo/pytorch-YOLOv4#50]
（1）此问题已解决，-dir路径+train.txt路径 = 图片路径，train.txt里的路径不全，不能imread到图像，调试就可以发现。
（2）此程序可以训练自己的数据集，需要修改models.py，修改如darknet下cfg修改方式。coco_annotatin.py需要修改，修改成自己图片路径及名称。如果单运行train.py的话，cfg.dataset_dir设成自己的路径。

**Comment by Nikumata** [comment]
同问，train.txt里存放了图片地址和标注信息，那么这个 -dir 输入的参数应该是什么路径呢？

**Comment by tongguanghong** [comment]
> 同问，train.txt里存放了图片地址和标注信息，那么这个 -dir 输入的参数应该是什么路径呢？我设置了图片的路径，就报另外的错误了
> ![image](https://user-images.githubusercontent.com/22295063/82728816-6f026480-9d25-11ea-9115-bb36a5a7c524.png)

请问一下，你这个问题解决了吗

**Comment by dhiyu** [comment]
> > 同问，train.txt里存放了图片地址和标注信息，那么这个 -dir 输入的参数应该是什么路径呢？我设置了图片的路径，就报另外的错误了
> > ![image](https://user-images.githubusercontent.com/22295063/82728816-6f026480-9d25-11ea-9115-bb36a5a7c524.png)
> 
> 请问一下，你这个问题解决了吗

train.txt中的路径只有一部分，你点开看一下，不全的话需要把路径补全，补的这部分放在dataset_dir里面就可以了
