### ISSUE TITLE
你好，我训练了13个epoch，用训练的图片去检测，但是推理的结果没有bbox框，也没有正确识别出物体

### ISSUE THREAD

**Issue by zh9369** [Tianxiaomo/pytorch-YOLOv4#51]
请问这是怎么回事呢？

**Comment by syg1996419** [comment]
测试的脚本怎么写呀

**Comment by zh9369** [comment]
运行demo.py即可

**Comment by dhiyu** [comment]
确实，我好像也遇到这个问题了

**Comment by 2033329616** [comment]
我用这里提供的权重进行推理，发现模型输出全是nan和-inf，不知道为什么？

**Comment by Dylanbron** [comment]
我也遇到了这个问题，我先是用yolov4.conv.137.pth作为预训练权重，训了几个epoch然后用evaluate_on_coco.py推理，发现都是-inf,没有bbox，然后会报错。
然后我用demo.py做推理，用的是yolov4.pth和我自己的checkpoints得到的list_feature里面是nan,然后图像上面也没生成bbox。
请问哪位大佬解决这个问题了吗

**Comment by Maxwell0710** [comment]
有人解决没
识别不到物体，有时候还会报错

**Comment by oreo-lp** [comment]
我训练出来的也识别不出来结果，也有点懵逼

**Comment by zengjianyou** [comment]
我也一样的问题，之前还以为我数据做错了

**Comment by ersheng-ai** [comment]
demo.py, demo_onnx.py and demo_trt.py and their dependencies are evolving.
Please pull the latest code and try inference again.
I will close this issue. Please open new issues if you get new inference problems.

**Comment by futureflsl** [comment]
一样自己训练的模型和作者提供的pth模型什么都检测不出来

**Comment by zuoyuwei** [comment]
同样的情况，是不是pth和weights模型文件需要做下转换

**Comment by futureflsl** [comment]
pth拿到其他框架测试不行，这说明训练的模型根本不能用，转换也没用

**Comment by zuoyuwei** [comment]
我可能有些细节没搞清楚，但我昨天又认真看了下文档README，发现自己训练出来的模型用models.py进行预测是可以检测出来框的
