### ISSUE TITLE
RuntimeError DoubleTensor FloatTensor

### ISSUE THREAD

**Issue by TWangQing** [Tianxiaomo/pytorch-YOLOv4#55]
![Snipaste_2020-05-24_23-58-25](https://user-images.githubusercontent.com/22674866/82758671-7d7e7800-9e1a-11ea-93d5-b19ad5c5c765.png)
When I implement the code, I met the problem.Can anyone help me ?
Thanks a lot,please !

**Comment by TWangQing** [comment]
请问有人遇到这个问题吗

**Comment by yfor1008** [comment]
我也遇到了这个问题, 难道是torch版本不对嘛 ?

**Comment by oreo-lp** [comment]
是数据格式的问题，你需要将floattensor转成doubletensor就行了。具体改哪边你debug一下

**Comment by TWangQing** [comment]
> 我也遇到了这个问题, 难道是torch版本不对嘛 ?

我按照它报的错改了一下，可以了

**Comment by yfor1008** [comment]
我之前使用的pytorch版本是0.4的, 升级成1.5以后就没有问题了.
