### ISSUE TITLE
Move to YOLOV7 or YOLOX project unmaintained

### ISSUE THREAD

**Issue by santi-mir** [Tianxiaomo/pytorch-YOLOv4#557]
-deleted-

**Comment by PrajwalCogniac** [comment]
Hey @mahnehsilla Please tell me this I am really struggling

**Comment by santi-mir** [comment]
@PrajwalCogniac  use yolov7 or yolox this project is unmaintained and does not work

**Comment by PrajwalCogniac** [comment]
Hey @mahnehsilla 
Thanks a lot for the reply, 
So the problem I am facing is I have to use yolov4 for inference. I don't have control over the training portion. 
My client gave me the .cfg and weights of yolo4 and I have to run inference on it. 
Also the format of .cfg for route layer is like this 
[route]
layers = -1
groups = 2
group_id = 1
Can I use the yolo7 or yolox to load the yolo4 weights and config ?
Also any help in navigating this will be deeply appreciated

**Comment by santi-mir** [comment]
No, you cant transfer the weights to yolox or yolov7 because the Neural Net Architectures are different shape, and  the weights can not be transferred to completely different shapes. The weights can only be transferred if one nn is extension of another, or the exact same shape.

It may be possible to do inference with this project, but you will have to share a notebook for me to help, and I can not be sure I can help.

The way to go is to pick yolov7 or yolox, train the NN so you get the new weights, and do inference with the model you trained i.e yolov7 or yolox.
