### ISSUE TITLE
How to count the number of params with custom configs?

### ISSUE THREAD

**Issue by M-Amrollahi** [Tianxiaomo/pytorch-YOLOv4#575]
I have a config file and I wanted to count the number of parameters on my Yolov4 model. How can I count the params?

**Comment by GeorgeTsio** [comment]
> I have a config file and I wanted to count the number of parameters on my Yolov4 model. How can I count the params?

Just after model initialization in models.py type this: summary(model, input_size=[1, 3, 416, 416]). Adjust it to your own input size. Don't forget: 1. pip install torchsummary
                     2. from torchsummary import summary

**Comment by M-Amrollahi** [comment]
Bests...
