### ISSUE TITLE
mAP

### ISSUE THREAD

**Issue by ssscj** [Tianxiaomo/pytorch-YOLOv4#85]
请问要怎么计算mAP呢，能添加这个功能吗，谢谢

**Comment by Dylanbron** [comment]
evaluate_on_coco 里面有在coco上算ap的代码，但是我算出来都是0，希望哪位帮忙看一下

**Comment by Dylanbron** [comment]
evaluate_on_coco 里面有在coco上算ap的代码，但是我算出来都是0，希望哪位帮忙看一下

**Comment by Tianxiaomo** [comment]
#80
