### ISSUE TITLE
使用tensorrt版进行测试

### ISSUE THREAD

**Issue by qybing** [Tianxiaomo/pytorch-YOLOv4#88]
按照你方式进行转成tensorrt模型，挺正常的，测试也挺正常的，过程中都没有报错，但是测试的速度比没加速时还要慢，请问我时哪里出现错误了吗

**Comment by ersheng-ai** [comment]
> 按照你方式进行转成tensorrt模型，挺正常的，测试也挺正常的，过程中都没有报错，但是测试的速度比没加速时还要慢，请问我时哪里出现错误了吗

The **yolo_forward** method is still now evolving. We have to make sure the correctness first and then fix the speed problem of. The yolo layer in the converted ONNX is over fragmented and should be improved. The latter post-processing including NMS may also be another bottle net.

You can post an issue with more detailed information on NVIDIA developer forum if you are registered there.

**Comment by ersheng-ai** [comment]
Pull the latest code, re-generate onnx and engine, and re-run the inference again.
I will close this. Open a new issue if you still have problems.
