### ISSUE TITLE
Route Layer implementation

### ISSUE THREAD

**Issue by ChengyuSheu** [Tianxiaomo/pytorch-YOLOv4#9]
Route layer is concatenation instead of summation. Am I missing something?
[original](https://github.com/AlexeyAB/darknet/blob/97df6ac2b46b9687d772ce3744ff7e6a5b7b4ba1/src/parser.c#L1018)
[yours](https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/6bae417d2b470b61151e469cadb5f1696288230f/models.py#L198)

**Comment by sporadicCactus** [comment]
Since layer.out_w and layer.out_h specify spatial dimensions, I suppose layer.out_c specifies the number of channels. The line you highlighted means we are summing the number of channels (concatenating).

**Comment by ChengyuSheu** [comment]
Exactly. Are you using summation in your implementation?

**Comment by sporadicCactus** [comment]
No, layer.out_c is the number of channels after routing.
So incoming layers have dimensions
[first.out_c, out_h, out_w], [second.out_c, out_h, out_w], ...
And after the routing the dimensions are
[first.out_c + second.out_c + ..., out_h, out_w].
This is compatible with concatenation.

Also note you are looking at the parser implementation. It doesn't do any operations on tensors yet, just figures out dimensions, activations etc. from the configuration file.

**Comment by ChengyuSheu** [comment]
Can do tell me more about the following code from your DownSample1 class?
Why do shortcut layer and route layer have the same operator +?
`2

       x6 = self.conv6(x5)
        x6 = x6 + x4                  # shortcut -3
        x7 = self.conv7(x6)
        x7 = x7 + x3                  # [route]         # layers = -1, -7`

**Comment by sporadicCactus** [comment]
I'm no author of this rep, so no idea.
The demos use the model defined in tool/darknet2pytorch.py. If you look at route and shortcut implementations there, you will see concatenation and summation respectively.

I am not sure whether the contents of model.py file are relevant at all.

**Comment by ChengyuSheu** [comment]
@sporadicCactus , thanks for your reply.
I thought models.py is where the author define the model. I didn't look into the demo.py and darknet2pytorch.py.

**Comment by syg1996419** [comment]
难道models.py不是主网络吗？

**Comment by bobo0810** [comment]
> 难道models.py不是主网络吗？

主网络是yolov4.cfg
