### ISSUE TITLE
model.py中定义的模型不可以用来做推理吗？

### ISSUE THREAD

**Issue by JunLeecus** [Tianxiaomo/pytorch-YOLOv4#92]
pytorch定义的模型返回
![image](https://user-images.githubusercontent.com/47651397/83889025-36c74100-a77d-11ea-9fb3-b2e78a872184.png)
是三层的检测结果，检测结果concat后不能直接调utils中的do_detect进行预测呀？看预测都是用的darknet骨架转换的
![image](https://user-images.githubusercontent.com/47651397/83889239-7726bf00-a77d-11ea-80c6-f8766eff85cf.png)
也就是说pytorch的模型只用于训练，推理还是用的darknet直接转换是吗？想要将pytorch模型用于推理能不能实现一下呢

**Comment by oreo-lp** [comment]
你可以创建一个Yolov4的实例对象，然后将训练好的权重加载进网络中进行推理。
   `   model = Yolov4(n_classes=2)` 
    ` model.load_state_dict(torch.load(weightfile))` 
    ` # use cuda` 
   `  device = torch.device('cuda:2' if torch.cuda.is_available() else 'cpu')` 
    ` model = model.to(device)`

然后加载图片或者视频进行推理就行了

**Comment by YSJ305** [comment]
> 你可以创建一个Yolov4的实例对象，然后将训练好的权重加载进网络中进行推理。
> ` model = Yolov4(n_classes=#your_classes)`
> ` model.load_state_dict(torch.load(weightfile))`
> ` # use cuda`
> ` device = torch.device('cuda:2' if torch.cuda.is_available() else 'cpu')`
> ` model = model.to(device)`
> 
> 然后加载图片或者视频进行推理就行了


可是在预测的时候还是会出现如下错误：

Traceback (most recent call last):
  File "models.py", line 464, in <module>
    boxes = do_detect(model, sized, 0.5, n_classes,0.4, use_cuda)
  File "D:\code_learning\pytorch-YOLOv4\tool\torch_utils.py", line 352, in do_detect
    output[-1].append(boxes_and_confs[i][1].cpu().detach().numpy())
IndexError: index 1 is out of bounds for dimension 0 with size 1

**Comment by oreo-lp** [comment]
post_process需要修改，检测也需要修改

**Comment by JJZHK** [comment]
Yolov4在与测试时候，没有经过YoloLayer的处理。在预测的时候，需要经过YoloLayer的处理，就可以得到正确的结果了。

**Comment by JJZHK** [comment]
yolo4在预测的时候，最后需要将结果从yoloLayer中走一遍，才能得到正确的结果。

**Comment by ersheng-ai** [comment]
**`models.py`** is now capable to do inference.
Please pull the latest code.
