### ISSUE TITLE
训练时，需要将代码中的YOLOLayer激活吗

### ISSUE THREAD

**Issue by danmuking** [Tianxiaomo/pytorch-YOLOv4#94]
![image](https://user-images.githubusercontent.com/47711726/83946079-4f992a80-a841-11ea-89a8-c63c629718f2.png)
在刚开始的时候yolo层被注释掉了，训练的时候需要打开吗

**Comment by danmuking** [comment]
> ![image](https://user-images.githubusercontent.com/47711726/83946079-4f992a80-a841-11ea-89a8-c63c629718f2.png)
> 在刚开始的时候yolo层被注释掉了，训练的时候需要打开吗

**Comment by ersheng-ai** [comment]
I added an extra argument named **`yolo_layer_included`**.
Its default value is **`False`**.
Use the default value when you do the training, set it to **`True`** when you do inference.

Please pull the latest code.
