### ISSUE TITLE
demo 预测dog.jpg的结果是原图，没有框

### ISSUE THREAD

**Issue by Libaididi** [Tianxiaomo/pytorch-YOLOv4#95]
中间有一个警告。
`D:\learnlearn\compete\yolo\pytorch-YOLOv4-master\tool\utils.py:20: RuntimeWarning: invalid value encountered in subtract
  x = np.exp(x - np.expand_dims(np.max(x, axis=1), axis=1))`

**Comment by ersheng-ai** [comment]
As I know the latest demo of master branch does not go to this part of source code.
If you are in the training branch, try to switch back to the master branch.
