### ISSUE TITLE
关于tgt_scale作用的疑问

### ISSUE THREAD

**Issue by oreo-lp** [Tianxiaomo/pytorch-YOLOv4#98]
代码如下：
https://github.com/Tianxiaomo/pytorch-YOLOv4/blob/39da4ec8dd2b6af6d9c3bf9a6dfb39be92a9a73b/train.py#L187

不是很理解tgt_scale这个变量的作用是什么？还请作者或者同行们能够不吝赐教

**Comment by oreo-lp** [comment]
这是变量的意思是给loss参数加上一个比例系数嘛？好像是这个意思？

**Comment by Arvin1201** [comment]
yolov4作者就是这样写的,目的就是为了减小小框的尺度误差

**Comment by yyaqi** [comment]
放大小尺度目标框误差对训练的影响，减小大尺度目标框误差对训练的影响

**Comment by oreo-lp** [comment]
非常感谢！
